version: 2.1

orbs:
  percy: percy/agent@0.1.3
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  node:
    docker:
      - image: cimg/python:3.9.9-node
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB

    steps:
      - checkout
      - restore_cache:
          key: node-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run: npm i

      - save_cache:
          key: node-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Run eslint
          command: ./node_modules/.bin/eslint src

  python-36: &test-template
    docker:
      - image: cimg/python:3.6.15-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PERCY_ENABLE: 1
          PERCY_PARALLEL_TOTAL: -1

    steps:
      - checkout
      - run: cat requirements.txt tests/requirements.txt demos/requirements.txt demos/*/requirements.txt > all-req.txt
      - run: python -c "import sys;print(sys.version)" > ver.txt
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "ver.txt" }}-{{ checksum "all-req.txt" }}
      - browser-tools/install-browser-tools

      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip wheel
            pip install -r requirements.txt -r tests/requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "ver.txt" }}-{{ checksum "all-req.txt" }}
          paths:
            - venv

      - run:
          name: Run black
          command: |
            . venv/bin/activate
            black usage* demos tests --check

      - run:
          name: Rendering Tests
          command: |
            . venv/bin/activate
            pytest --nopercyfinalize tests/test_render.py

      - run:
          name: Percy Snapshot Tests
          command: |
            . venv/bin/activate
            pytest --nopercyfinalize tests/test_percy.py

      - store_artifacts:
          path: /tmp/dash_artifacts
          destination: snapshots

  python-39:
    <<: *test-template
    docker:
      - image: cimg/python:3.9.9-browsers
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PERCY_ENABLE: 0

workflows:
  version: 2
  build:
    jobs:
      - python-36
      - python-39
      - node
      - percy/finalize_all:
          requires:
            - python-36
